enactor:
  ros__parameters:
    # Operation parameters
    frequency: 1.0                   # Control loop frequency (Hz)
    kp: 0.5                          # Proportional gain for control
    adaptation_parameter: "reliability"  # Default parameter: "reliability" or "cost" 
    stability_margin: 0.02           # Minimum error before applying adaptation (deadband)
    
    # Adaptation parameters
    min_frequency: 0.1               # Minimum component frequency (Hz)
    max_frequency: 10.0              # Maximum component frequency (Hz)
    min_replicate_task: 1            # Minimum task replication level
    max_replicate_task: 10           # Maximum task replication level
    
    # Control thresholds
    reliability_threshold: 0.95      # Default reliability threshold
    cost_threshold: 0.2              # Default cost threshold
    
    # Fault tolerance
    retry_command_attempts: 2        # Number of times to retry failed commands
    retry_delay: 0.5                 # Delay between retry attempts (seconds)
    
    # Safety parameters
    emergency_shutdown_reliability: 0.5  # Reliability threshold for emergency shutdown
    emergency_shutdown_battery: 10.0     # Battery level for emergency shutdown
    
    # Component parameters
    default_frequency: 1.0           # Default component frequency
    
    # Component configuration
    components:
      - name: "g3t1_1"               # Thermometer
        initial_frequency: 1.0
        initial_replicate_task: 1
        reliability_target: 0.95
        cost_target: 0.2
      - name: "g3t1_2"               # ECG
        initial_frequency: 1.0
        initial_replicate_task: 1
        reliability_target: 0.98     # Higher reliability target for critical component
        cost_target: 0.15
      - name: "g3t1_3"               # Oximeter
        initial_frequency: 1.0
        initial_replicate_task: 1
        reliability_target: 0.95
        cost_target: 0.2
      - name: "g3t1_4"               # ABP Systolic
        initial_frequency: 1.0
        initial_replicate_task: 1
        reliability_target: 0.95
        cost_target: 0.2
      - name: "g3t1_5"               # ABP Diastolic
        initial_frequency: 1.0
        initial_replicate_task: 1
        reliability_target: 0.95
        cost_target: 0.2
      - name: "g3t1_6"               # Glucometer
        initial_frequency: 0.5       # Lower frequency for non-critical component
        initial_replicate_task: 1
        reliability_target: 0.9      # Lower reliability target
        cost_target: 0.25           # Higher acceptable cost