patient:
  ros__parameters:
    frequency: 10.0
    vitalSigns: ["oxigenation", "heart_rate", "temperature", "abps", "abpd", "glucose"]

    oxigenation_Change: 0.2
    heart_rate_Change: 0.1
    temperature_Change: 0.1
    abps_Change: 0.1
    abpd_Change: 0.1
    glucose_Change: 0.1

    oxigenation_Offset: 10.0
    heart_rate_Offset: 10.0
    temperature_Offset: 10.0
    abps_Offset: 10.0
    abpd_Offset: 10.0
    glucose_Offset: 10.0

    oxigenation_State0: [0.0, 0.0, 0.0, 0.0, 0.0]
    oxigenation_State1: [0.0, 0.0, 0.0, 0.0, 0.0]
    oxigenation_State2: [0.0, 0.0, 90.0, 8.0, 2.0]
    oxigenation_State3: [0.0, 0.0, 75.0, 10.0, 5.0]
    oxigenation_State4: [0.0, 0.0, 5.0, 35.0, 60.0]

    oxigenation_HighRisk0: [-1.0, -1.0]
    oxigenation_MidRisk0: [-1.0, -1.0]
    oxigenation_LowRisk: [65.0, 100.0]
    oxigenation_MidRisk1: [55.0, 65.0]
    oxigenation_HighRisk1: [0.0, 55.0]

    heart_rate_State0: [72.0, 21.0, 4.0, 2.0, 1.0]
    heart_rate_State1: [14.0, 61.0, 19.0, 4.0, 2.0]
    heart_rate_State2: [1.0, 17.0, 60.0, 20.0, 2.0]
    heart_rate_State3: [0.0, 2.0, 15.0, 70.0, 13.0]
    heart_rate_State4: [0.0, 1.0, 2.0, 20.0, 77.0]

    heart_rate_HighRisk0: [0.0, 70.0]
    heart_rate_MidRisk0: [70.0, 85.0]
    heart_rate_LowRisk: [85.0, 97.0]
    heart_rate_MidRisk1: [97.0, 115.0]
    heart_rate_HighRisk1: [115.0, 300.0]

    temperature_State0: [25.0, 51.0, 21.0, 3.0, 0.0]
    temperature_State1: [5.0, 50.0, 43.0, 2.0, 0.0]
    temperature_State2: [0.0, 4.0, 85.0, 11.0, 0.0]
    temperature_State3: [0.0, 1.0, 32.0, 67.0, 0.0]
    temperature_State4: [0.0, 0.0, 0.0, 0.0, 0.0]

    temperature_HighRisk0: [0.0, 31.99]
    temperature_MidRisk0: [32.0, 35.99]
    temperature_LowRisk: [36.0, 37.99]
    temperature_MidRisk1: [38.0, 40.99]
    temperature_HighRisk1: [41.0, 50.0]

    abpd_State0: [0.0, 0.0, 0.0, 0.0, 0.0]
    abpd_State1: [0.0, 0.0, 0.0, 0.0, 0.0]
    abpd_State2: [0.0, 0.0, 94.0, 4.0, 2.0]
    abpd_State3: [0.0, 0.0, 50.0, 35.0, 15.0]
    abpd_State4: [0.0, 0.0, 31.0, 25.0, 44.0]

    abpd_HighRisk0: [-1.0, -1.0]
    abpd_MidRisk0: [-1.0, -1.0]
    abpd_LowRisk: [0.0, 80.0]
    abpd_MidRisk1: [80.0, 90.0]
    abpd_HighRisk1: [90.0, 300.0]

    abps_State0: [0.0, 0.0, 0.0, 0.0, 0.0]
    abps_State1: [0.0, 0.0, 0.0, 0.0, 0.0]
    abps_State2: [0.0, 0.0, 79.0, 18.0, 3.0]
    abps_State3: [0.0, 0.0, 23.0, 64.0, 13.0]
    abps_State4: [0.0, 0.0, 5.0, 26.0, 69.0]

    abps_HighRisk0: [-1.0, -1.0]
    abps_MidRisk0: [-1.0, -1.0]
    abps_LowRisk: [0.0, 120.0]
    abps_MidRisk1: [120.0, 140.0]
    abps_HighRisk1: [140.0, 300.0]

    glucose_State0: [20.0, 40.0, 22.0, 15.0, 3.0]
    glucose_State1: [10.0, 50.0, 20.0, 15.0, 5.0]
    glucose_State2: [4.0, 9.0, 65.0, 12.0, 10.0]
    glucose_State3: [0.0, 2.0, 33.0, 50.0, 15.0]
    glucose_State4: [0.0, 0.0, 20.0, 45.0, 35.0]

    glucose_HighRisk0: [20.0, 39.99]
    glucose_MidRisk0: [40.0, 54.99]
    glucose_LowRisk: [55.0, 95.99]
    glucose_MidRisk1: [96.0, 119.99]
    glucose_HighRisk1: [120.0, 200.0]
