# .github/workflows/ci.yaml
name: Docker ROS 2 Jazzy CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  docker-build-and-test:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      run: |
        docker build -t bsn2:latest .

    - name: Run tests inside Docker container
      run: |
        docker run --rm bsn2:latest bash -c "
          source /opt/ros/jazzy/setup.bash && \
          source /ros_ws/install/setup.bash && \
          colcon test --event-handlers console_direct+ --return-code-on-test-failure
        "
